# _config.yml

name: Lê Việt Thành
description: "Sinh viên năm 2 (19 tuổi) | AI & Software Engineering"
url: "https://levietthanh1412.github.io" # Thay đổi URL của bạn

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Các cấu hình khác...